### ISSUE TITLE
根据客户端请求的ip选择出站

### ISSUE THREAD

**Issue by clcc2019** [0x676e67/vproxy#33]
可以根据客户端请求的ip选择出站？比如curl -x http://[IPv6-a]:8100 https://ifconfig.me，这里代理使用IPv6-a出站获取IPv6-a地址

**Comment by gngpp** [comment]
不在规范内，前提是用户得知道IP段

**Comment by gngpp** [comment]
一种方式是，IP段内的指定IP作为用户名发送，前提是用户得知道IP段

**Comment by clcc2019** [comment]
> 不在规范内，前提是用户得知道IP段

是的，可以拿到cidr自定义代理地址，这样可以定制落地ip，随机ip容易风控
