### ISSUE TITLE
IS IT SUPPORTING UDP PROTOCOL OF SOCKS 5 OR NOT?

### ISSUE THREAD

**Issue by subugt** [0x676e67/vproxy#36]
if not then are you planning to add a support

**Comment by 0x676e67** [comment]
You can check the code, I haven't tested it

**Comment by subugt** [comment]
okay sir i will

**Comment by subugt** [comment]
> You can check the code, I haven't tested it

I am not rust expert would you help me? or i have to wait a little more

**Comment by 0x676e67** [comment]
It's okay, you can use udp client for testing

**Comment by subugt** [comment]
ohh okay also i want to ask you i have a network coffe and i want to convert my pcs to socks 5 which one supports udp protocol so its like a server/client and i will rent my network to a proxy provider in nights can you make me application like this or how can i make it ( just open a port socks 5 - udp then use it thats all i am asking )

> It's okay, you can use udp client for testing

**Comment by 0x676e67** [comment]
command: vproxy run socks5 -u your_name -p your_pass，default port 8100

**Comment by subugt** [comment]
thanks you for helping me i am alr leave a star ❤️
