### ISSUE TITLE
http proxy must return proper response status

### ISSUE THREAD

**Issue by deba12** [0x676e67/vproxy#39]
Http proxy must return proper response codes when unable to authorize/authenticate/fulfill the request.
Optionally string with proper error information

When the ipaddress is not in the whitelist and username/password are missing
```
403 Forbidden
```
When the username/password are wrong
```
407 Proxy Authentication Required
```
When unable to complete the request (missing dns name, or other errors)
```
500 Internal Server Error
```
When unable to connect to the remote server
```
502 Bad Gateway
```
When connection times out
```
504 Gateway Timeout
```

**Comment by 0x676e67** [comment]
I think you can learn rust for PR, I don't have so much time to deal with such detailed request specifications

**Comment by 0x676e67** [comment]
https://doc.rust-lang.org/book/
