### ISSUE TITLE
Clarify how whitelist and authentication works

### ISSUE THREAD

**Issue by deba12** [0x676e67/vproxy#40]
When comparing vproxy to the other proxy servers, there is huge difference how their whitelist and authentication works.

Whitelist is used when ips are allowed to use the proxies with no username+password when they are in the whitelist
Username+password is used when proxy is accessed with username+password

With vproxy as far I can see, there is not that way.
if I don't use -w switch (for whitelist) I see everyone can use my proxy, this is nightmare if someone 
miss configures his proxy. Open and unrestricted proxy for every one! Imagine how much abuse and spam will be send through this proxy

I would recommend following changes

- By default if -w is not present and no username+password provided by the client - reject the request.
- if -w is present and the connection comes from whitelisted ip addresses - allow the request
- If -u and -p switches are present - allow the request if the username+password matches with -u/-p

This gives you clearly who and how will have access to the proxy server.

**Comment by 0x676e67** [comment]
There is a loophole in the logic at the moment and I will fix it. But in any case, when the user uses passwordless authorization, anyone can use it, this reservation is reserved only for those who need it. But when the whitelist exists, as a restriction, only users in the whitelist, or people authorized with the correct password can access the proxy.

**Comment by 0x676e67** [comment]
Each proxy should retain the functionality of authorized and unauthorized access, rather than leaving it to a custom whitelist to handle authorization issues.
