### ISSUE TITLE
Add switch to disable ipv4 traffic forward

### ISSUE THREAD

**Issue by deba12** [0x676e67/vproxy#41]
At the moment if I try to use "socks5" as proxy (dns resolving happens on client side)
I see my ipv4 address is used
```sh
# curl -x "socks5://test:test@xxx.xxx.xxx.161:8101" ifconfig.co
xxx.xxx.xxx.161
```

Please add switch to completely disable ipv4 proxy traffic, or you are risking the proxy ipv4 address leak when remote sites have mixed ipv4/ipv6 addresses

**Comment by 0x676e67** [comment]
I retain this function just to allow the API to be accessed correctly. For interfaces that do not support ipv6, the system proxy request will be returned by default.

I think since the proxy is given to other users, what is the important connection with the IP being known? Even IPv4/IPv6

**Comment by 0x676e67** [comment]
use remote resolve
```shell
curl -x "socks5h://test:test@xxx.xxx.xxx.161:8101" ifconfig.co
```

**Comment by 0x676e67** [comment]
I will modify the policy, 1. When CIDR exists, only use CIDR range addresses. 2. When CIDR and fallback addresses exist, the CIDR range address will be used. If the link to the target address fails, it will fall back to the fallback address. 3. If neither of the above two exists, use the system default proxy.
