### ISSUE TITLE
Request Features

### ISSUE THREAD

**Issue by xiaozhou26** [0x676e67/vproxy#78]
Request Features:
Assign a /64 subnet segment to be used in a fixed manner through the /48 subnet segment of the server

**Comment by 0x676e67** [comment]
你来做

**Comment by xiaozhou26** [comment]
> 你来做

更改哪个部分

**Comment by xiaozhou26** [comment]
#79

**Comment by 0x676e67** [comment]
我没看懂你这写的是什么，你是想每次分配不同/64？

**Comment by xiaozhou26** [comment]
> 我没看懂你这写的是什么，你是想每次分配不同/64？
每次启动的时候，分配一个固定的/64，之后每次请求都是这个网段。重启重新获取一个网段

**Comment by 0x676e67** [comment]
这个用session就能解决了，为什么要重启

**Comment by 0x676e67** [comment]
/48就只能分2^16个/64

**Comment by xiaozhou26** [comment]
你用session解决什么？我要的每次一个固定网段的/64，你那session还是随机/48

**Comment by xiaozhou26** [comment]
> /48就只能分2^16个/64

这用得着你说？

**Comment by 0x676e67** [comment]
这叫随机？你固定session不就好了
<img width="933" alt="image" src="https://github.com/user-attachments/assets/a0ad95bc-4463-422c-be36-de9c5d92c0e0">

**Comment by 0x676e67** [comment]
/64 后面变有什么意义？，你是想用在openai上吧，/64就算一个地址

**Comment by 0x676e67** [comment]
你是想要这样？
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/fe5097a7-cd84-46ce-b604-a585fae984a2">

**Comment by xiaozhou26** [comment]
？
